[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Ensure all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200