[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Ensure all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200