[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200